### ISSUE TITLE
Logout on remix example doesn't work

### ISSUE THREAD

**Issue by moity** [slashid/javascript#263]
I followed this guide to create a remix example with SlashId: https://developer.slashid.dev/docs/access/remix-sdk/tutorials/quick-start

Everything works, can login and determine that the user is logged in, but clicking a logout button which invokes logOut from useSlashID() does nothing, it seems to revalidate the page, but the user remains authenticated/logged in.

Here's my simplified code:

```
export const loader: LoaderFunction = slashIDRootLoader(async (args: any) => {
  
  if (args.request.url.includes("/login")) {
    return {};
  }
  const user = getUser(args);  
  if (!user) {
    return redirect("/login");
  }

  return { user };
});

export default function App() {
   const { logOut } = useSlashID();

   return (
      <html lang="en">
         <head></head>
         <body>
         <SlashIDApp>
            <div className="topnav">
               <LoggedIn>
                   <Link to="/">Home</Link>
                   <Link to="/about">About</Link>
                   <button onClick={logOut}>Log out</button>
                </LoggedIn>
              </div>
              <Outlet />
           </SlashIDApp>
      </body>
</html>);
}
```

**Comment by ikovic** [comment]
Thanks for reporting this @moity - we'll take a look!

**Comment by ikovic** [comment]
@moity at a quick glance, the problem seems to be consuming the `useSlashID` hook outside of the context - notice how in this example `<App>` consumes the hook as a parent of `<SlashIDApp>`?

This hook (and any other SlashID component) needs to have the `SlashIDApp` as an ancestor, because it provides the required context for it.

So in order to solve this issue, you can create a dedicated `LogOut` component and render it like this:

```
function LogOut() {
  const { logOut } = useSlashID();

  return <button onClick={logOut}>Log out</button>
}

export const loader: LoaderFunction = slashIDRootLoader(async (args: any) => {  
  if (args.request.url.includes("/login")) {
    return {};
  }
  const user = getUser(args);  
  if (!user) {
    return redirect("/login");
  }

  return { user };
});

export default function App() {
   return (
      <html lang="en">
         <head></head>
         <body>
         <SlashIDApp>
            <div className="topnav">
               <LoggedIn>
                   <Link to="/">Home</Link>
                   <Link to="/about">About</Link>
                   <LogOut />
                </LoggedIn>
              </div>
              <Outlet />
           </SlashIDApp>
      </body>
</html>);
}
```

Now the `SlashIDApp` is an ancestor of the `LogOut` component, so the hook will produce the correct result.

I think we can improve the dev experience by throwing a dev friendly error if the hook is consumed outside the required context, that would make the solution more straightforward. What do you think?

**Comment by moity** [comment]
Apologies I meant to come back sooner, your analysis was correct and resolved my issue. Thank you for the very prompt reply.
